# Generated by Django 4.0 on 2021-12-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverallScopus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarlyOutputOverall', models.TextField(blank=True)),
                ('authorsOverall', models.TextField(blank=True)),
                ('citationsOverall', models.TextField(blank=True)),
                ('citationsPerPubOverall', models.TextField(blank=True)),
                ('createdAtFirst', models.DateTimeField(auto_now_add=True)),
                ('updatedAtFirst', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
