# Generated by Django 4.0 on 2022-04-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number', default=2000)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('sch_output', models.IntegerField(db_column='sch_output', default=2000)),
                ('year', models.IntegerField(db_column='year', default=2000)),
                ('citations', models.IntegerField(db_column='citations', default=2000)),
                ('h_index', models.IntegerField(db_column='h_index', default=2000)),
            ],
            options={
                'verbose_name': 'Researchers',
                'verbose_name_plural': 'Researchers',
                'db_table': 'researchers',
            },
        ),
        migrations.DeleteModel(
            name='OverallScopus',
        ),
    ]
